# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RACCommand' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ReactiveObjC', '~> 3.0.0'
  # Pods for RACMulticastConnection

  target 'RACCommandTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RACCommandUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
