# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RAC常用宏' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'ReactiveObjC', '~> 3.0.0'
  # Pods for RAC常用宏

  target 'RAC常用宏Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RAC常用宏UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
